import { Geist} from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar/Navbar";
import Footer from "@/component/Footer/Footer";
import { ToastContainer } from "react-toastify";
import TimelineProvider from "@/context/TimelineContext";


const geist = Geist({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // optional
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light"
      className={`h-full antialiased`}
    >
      <body className={`h-full ${geist.className}`}>
       
         <TimelineProvider>
           <Navbar />
          {children}
           <ToastContainer />
          <Footer />
        </TimelineProvider>
       
      </body>
    </html>
  );
}
